In [2]:
import pickle

In [7]:
keys=['image_seq', 'depth_seq', 'motion_seq', 'intrinsics']
EleList=[10,15,20,35]

In [8]:
d={}

In [9]:
d['image_seq']=EleList[0]
d['lol']=EleList[1]
d['abc']=EleList[2]

In [10]:
d

{'image_seq': 10, 'lol': 15, 'abc': 20}

In [4]:
import numpy as np
list_1=[]

A=np.random.random((3,3))
B=np.random.random((3,3))
C=np.random.random((3,3))

In [6]:
list_1.append(A)
list_1.append(B)
list_1.append(C)

In [7]:
list_1

[array([[0.89567715, 0.08131778, 0.23962369],
        [0.23026452, 0.84830013, 0.78074879],
        [0.13089135, 0.22074189, 0.94665653]]),
 array([[0.89567715, 0.08131778, 0.23962369],
        [0.23026452, 0.84830013, 0.78074879],
        [0.13089135, 0.22074189, 0.94665653]]),
 array([[0.23552773, 0.19169539, 0.87346662],
        [0.14761581, 0.41562587, 0.22515409],
        [0.87098443, 0.72098065, 0.65466407]]),
 array([[0.29192634, 0.97728831, 0.40671789],
        [0.10825522, 0.55800126, 0.91574982],
        [0.31788236, 0.33173455, 0.53540737]])]